image:
  name: ovalbsol/java-maven:17.3.8.4
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD

pipelines:
  branches:
    master:
      - step: &Install
          name: Install
          script:
            - echo "<settings><servers><server><id>github</id><username>${GITHUB_USER}</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > .m2/settings.xml
            - mvn clean install -DskipTests -s .m2/settings.xml
          artifacts:
            - .m2/settings.xml
            - target/*
            - target/**/*
  tags:
    '*.*.*':
      - step: *Install
      - step:
          name: Build
          script:
            - mvn package -DskipTests -s .m2/settings.xml
          artifacts:
            - .m2/settings.xml
            - target/*
            - target/**/*
      - step:
          name: Deploy
          script:
            - mvn deploy -DskipTests -s .m2/settings.xml